#- name: Auto Assign Action
#  uses: kentaro-m/auto-assign-action@v1.1.2

name: 'Auto Assign'
on: pull_request_target

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        #with:
        #  configuration-path: ".github/some_name_for_configs.yml" # Only needed if you use something other than .github/auto_assign.yml
